Search added. Tests successful.
pavlovartem97/java-filmorate pull request #16
Opened 2023-04-16 15:44 UTC by boltaevt

2023-04-16 19:14 UTC, pavlovartem97 requested changes
Не самый лучший подход, когда достаем из таблицы сразу все фильмы, а потом проводим сортировку коллекции. В высоконагруженной БД может быть очень много фильмов и твой запрос надолго ее затормозит + займет очень много оперативной памяти и сами функции фильтрации O(N) будут долго выполняться. Такое наш ревьюер точно не зачет, предлагаю переделать. Всю работу должен брать на себя SQL - https://techrocks.ru/2023/03/29/how-to-locate-a-substring-in-a-string-in-sql/ . Существует способ сразу отфильтровать по значению.

Так же необходимо добавить тесты на новый функционал

2023-04-16 19:19 UTC, pavlovartem97 commented
Так же можешь глянуть ревью Вадима. У него как раз что-то похожее с фильтрами и решение намного лучше. Можно в зависимости от того по чему происходит поиск менять наш SQL. В таком случае вообще достаточно добавить всего 1 функцию в Storage, которая принимает подстроку и по чему ищем. В зависимости от того по чему ищем подучается разный запрос. В сервисах тогда будет 1 функция с обращением к базе

2023-04-18 11:25 UTC, pavlovartem97 reviewed
По функционалу все хорошо, остались небольшие стилистические правки

2023-04-18 11:25 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            throw new RuntimeException("Unacceptable query.");
Выброс ошибки вынести на уровень сервисов. Там же можно провалидировать по аналогии с функциями check, чтобы сюда попадали только валидные данные

2023-04-18 11:25 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    " ORDER BY rating desc, f.film_id) fl JOIN MPA m ON fl.mpa_id = m.MPA_ID";
![image](https://user-images.githubusercontent.com/111424160/232760753-6571dea3-d30a-4f55-9d91-c28d6fa977b9.png)
У тебя тут идут 3 запроса, которые отличаются друг от друга в 2-4 строчках в одном и том же месте. Попробуй скомпоновать вею строку запроса из 3-х частей, где 2-я часть изменяемая в зависимости от условия.

2023-04-18 11:25 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +            throw new RuntimeException("Unacceptable query.");
Будет лучше добавить новую ошибку UnacceptableQueryException

2023-04-18 11:25 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    " COUNT(fv.user_id) rating FROM film f LEFT JOIN favourite fv ON f.film_id = fv.film_id " +
Запросы хорошие, но лучше привести в более читаемый вид:
1. Вторая строчка начинается с FROM. Нехорошо туда отправлять COUNT(fv.user_id)
2. LEFT JOIN DIRECTOR d ON fd.DIRECTOR_ID = d.DIRECTOR_ID не надо разбивать на 2 строчки
и тд.

2023-04-18 14:05 UTC, Anton-Lazarev reviewed
Хорошая работа.
Замечания такие же ,как и у Артёма.
SQL запрос наверное лучше собирать через StringBuilder из 3-х частей перед тем, как его в JdbcTemplate использовать.

2023-04-18 16:18 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (by.size() == 2) {
Не совсем правильно понял идею со StringBuilder. Такого точно не нужно делать). Нужно было сразу всею строку зааппендить. Потом зааппендить всю конечную строку. В текущей версии действительно ничего не понятно)

2023-04-18 16:18 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (by.size() == 2) {
sql.append и дальше всю строчку середины запроса

2023-04-18 16:20 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (by.size() == 2) {
Комментарий Антона: "SQL запрос наверное лучше собирать через StringBuilder из 3-х частей перед тем, как его в JdbcTemplate использовать."

2023-04-18 16:28 UTC, Anton-Lazarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        if (by.size() == 2) {
Должно было получиться в конце то что типа sql.append(midleOfQuery).append(endOfQuery)

Если у тебя сложности со StringBuilder, то и собирал бы как собирал через "+", тут вариантов решения несколько. Главный посыл был - держать две локальные String в методе, которые неизменны (начало и конец), а в if подкидывать только нужную середину.

2023-04-18 20:33 UTC, Anton-Lazarev commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                    " AND f2.FILM_ID = f.FILM_ID) " +
Эту часть запроса можно вынести из if: " AND f2.FILM_ID = f.FILM_ID) " +
                    " GROUP BY f.film_id " +
                    " ORDER BY rating desc, f.film_id) fl JOIN MPA m ON fl.mpa_id = m.MPA_ID"
                    
 Это как минимум сэкномит несколько строк кода и не будет дублирования.

2023-04-18 21:05 UTC, pavlovartem97 approved these changes

2023-04-19 08:57 UTC, merged