Add friends likes
pavlovartem97/java-filmorate pull request #8
Opened 2023-03-03 19:45 UTC by pavlovartem97

2023-03-04 10:24 UTC, kalitva requested changes

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private final FilmValidator filmValidator;
Логику по валидированию нужно переместить в сервисы

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Контроллер не должен напрямую обращаться к стораджу, только через сервис, по сути методы контроллера практически не содержит логики, только маппинги http запросов и вызовы методов сервиса

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Film list getting " + filmStorage.getAllFilm());
Логирование нужно перенести в сервисы

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new RuntimeException("Path variable should contain id and userId");
Нет необходимости использовать `Optional` и бросать исключение, если параметр пути не указан. Спринг сам обработает эту ситуацию, выбросив исключение,  и вернет статус 404 (или 400, точно не помню)

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          film.setId(++filmId);
Теперь это должно делаться в сторадже

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likesId = new HashSet<>();
`likesId --> likeIds`

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesId == null){
Этот хэшсет не может быть нулем, так как мы его инициализируем при объявлении

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikesId().remove(user);
`film.getLikesId().remove(userId);`

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return intersection.stream().map(id -> userStorage.getUserById(id)).collect(Collectors.toList());
Форматируй стрим также, как в методе ниже

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(id -> userStorage.getUserById(id))
Лучше
`.map(userStorage::getUserById)`

2023-03-04 10:24 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Используй guard clause для валидации, это уменьшит уровень вложенности (здесь не очень принципиально, но вообще правильно именно так). Наведи курсор на условие, затем alt + enter --> invert condition. Потом уберешь else

```
        if (!films.containsKey(film.getId())) {
            throw new FilmNotFoundException("Film with Id " + film.getId() + " not found");
        }
        films.put(film.getId(), film);
```
https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-03-04 13:02 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesId == null){
![image](https://user-images.githubusercontent.com/111424160/222903407-7e5cb7c9-b90e-4816-aff4-1e0cf91154ee.png)

2023-03-04 13:03 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesId == null){
Если убрать логику в getLikesId(), то к сожалению не происходит инициализации поля likesId

2023-03-04 16:11 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesId == null){
Сделай поле final, тогда инициализация не будет слетать

2023-03-05 13:37 UTC, pavlovartem97 commented
Спасибо за хорошее ревью, поправил все баги

2023-03-05 13:54 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (likesId == null){
Спасибо, помогло решить проблему

2023-03-05 18:09 UTC, kalitva approved these changes

2023-03-05 18:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((film1, film2) -> film2.getLikeIds().size() - film1.getLikeIds().size())
Можешь воспользоваться встроенными компараторами
`.sorted(Comparator.comparing(f -> f.getLikeIds().size(), Comparator.reverseOrder()))`

2023-03-05 18:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Лишняя пустая строка

2023-03-05 18:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> commonFriends = intersection.stream().map(userStorage::getUserById).collect(Collectors.toList());
Форматируй стрим таким образом

```
        List<User> commonFriends = intersection.stream()
                .map(userStorage::getUserById)
                .collect(Collectors.toList());
```

2023-03-05 18:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Лишние пустые строки

2023-03-05 18:09 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private static int filmId;
Поля объявляются перед методами, причем статические перед инстанс полями

2023-03-05 18:44 UTC, merged