Add database features
pavlovartem97/java-filmorate pull request #9
Opened 2023-04-02 17:17 UTC by pavlovartem97

2023-04-03 19:42 UTC, kalitva requested changes

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/favourite/InMemoryFavouriteStorage.java
> +public class InMemoryFavouriteStorage implements FavouriteStorage {
Предлагаю все инмемори стораджи удалить, они не нужны и только мешают

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        for (Genre genre : film.getGenres()) {
Используй `JdbcTemplate#batchUpdate` для обновления списка объектов

https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#jdbc-advanced-jdbc

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
Нужно еще удалить жанры фильма

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmExtractor.java
> +        while (rs.next()) {
Вообще, когда поле объекта список, допустимо вытягивать его отдельным запросом, но так тоже норм)

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendDbStorage.java
> +public class FriendDbStorage implements FriendStorage {
Предлагаю все это переместить в `UserStorage`, а этот класс удалить

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, row) -> makeGenre(rs), id).stream().findAny()
Используй `JdbcTemplate#queryForObject` чтобы достать один объект, а не список

2023-04-03 19:42 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return jdbcTemplate.query(sql, userMapper, id).stream().findAny()
`JdbcTemplate#queryForObject`

2023-04-03 19:42 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA CASCADE;
Не думаю, что это хорошая удалять все данные при запуске приложения

2023-04-03 19:42 UTC, kalitva commented on src/main/resources/data.sql
> +INSERT INTO mpa (mpa_name)
Используй `MERGE` вместо `INSERT` это позволит не удалять все данные при запуске

2023-04-03 19:42 UTC, kalitva commented on src/main/resources/test-data.sql
Положи этот файл в `src/test/resources`

2023-04-03 19:46 UTC, kalitva commented
Отличная работа. Если появятся вопросы по ревью, пиши в чате

2023-04-03 20:23 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (this == o) return true;
Данный код был сформирован Idea автоматически, но хорошо поправлю

2023-04-03 20:24 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return id.equals(film.id);
Каждый фильм/юзер хранится в базе по своему уникальному ID. Значит для ускорения вычислений достаточно сравнивать по уникальной компоненте. Может быть 2 фильма с одинаковыми именами, описаниями и тд, но имеющие разные уникальные ID

2023-04-03 20:27 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          Film film = filmStorage.getFilmById(filmId);
Просто для подобной проверки и нахождения фильма используется один и тот же запрос. Чтобы не дублировать код и ошибку и не делать повторное выбрасывание ошибки, было принято решения оставить все в 1 методе getFilmById. Довольно распространенный подход (у нас применяется на работе)

2023-04-03 20:27 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          Film film = filmStorage.getFilmById(filmId);
Единственное, над чем раздумывал это сделать findFilmById Optional

2023-04-03 20:28 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +@Slf4j
Поправлю

2023-04-03 20:29 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    @Qualifier("userDbStorage")
Да, я заметил. Просто забыл удалить. Решил делать везде через AllArgsConstractor, а необходимые реализации пометил @Primary

2023-04-03 20:29 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/favourite/FavouriteDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.favourite;
Поправлю

2023-04-03 20:31 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/favourite/FavouriteDbStorage.java
> +public class FavouriteDbStorage implements FavouriteStorage {
Делал так изначально, но потом принял решение о разделении логики. Так получилось из-за двух реализаций, включая InMemory. + отдельный интерфейс для логических блоков, имеющих собственные таблицы в БД

2023-04-03 20:32 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/favourite/InMemoryFavouriteStorage.java
> +public class InMemoryFavouriteStorage implements FavouriteStorage {
Наоборот было потрачено немало времени, чтобы попытаться их сохранить в каком-то виде на уровне работы прошлого ТЗ

2023-04-03 20:36 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        for (Genre genre : film.getGenres()) {
Спасибо, переделаю

2023-04-03 20:37 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
Спасибо, добавлю

2023-04-03 20:40 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendDbStorage.java
> +public class FriendDbStorage implements FriendStorage {
Наоборот было потрачено немало времени, чтобы попытаться их сохранить в каком-то виде на уровне работы прошлого ТЗ. В данном случае придется сильно менять архитектуру

2023-04-03 20:40 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, row) -> makeGenre(rs), id).stream().findAny()
Спасибо, поправлю

2023-04-03 20:41 UTC, pavlovartem97 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA CASCADE;
Хорошо, когда нужно многократно запускать постман на локальной машине и не очищать БД вручную перед каждым запускам. В реальном проекте такого бы не было

2023-04-03 20:44 UTC, pavlovartem97 commented
Большое спасибо за замечания по ревью. Часть замечаний счел спорным и требующим больших изменений в архитектуре кода. Не считаю, что мой вариант самый лучший, просто он имеет право на существование. Часть логики была специально реализована таким образом, чтобы имелась поддержка второго варианта с InMemoryStorage

2023-04-03 21:09 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
constraint "FILM_GENRE_FILM_FILM_ID_fk"
        foreign key (FILM_ID) references FILM
            on delete cascade,
    constraint "FILM_GENRE_GENRE_GENRE_ID_fk"
        foreign key (GENRE_ID) references GENRE
            on delete cascade,

2023-04-03 21:11 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
Я протестировал. Так как стоит каскадное удаление, то жанры данного фильма автоматически удаляются при потере ссылок. Так же будет, если вдруг удалить сам жанр. Аналогично список другей пользователя автоматически отчистится при удалении пользователя

2023-04-03 21:20 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmExtractor.java
> +        while (rs.next()) {
https://devmark.ru/article/result-set-extractor

2023-04-03 21:22 UTC, pavlovartem97 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmExtractor.java
> +        while (rs.next()) {
Единственный недостаток, что ResultSetExtractor не является параметром JdbcTemplate#queryForObject. Что означает, что для фильмов все останется в таком виде. Во всех остальных местах поменял с использованием конструкции try, catch для выбрасывания собственных ошибок

2023-04-03 21:41 UTC, pavlovartem97 commented on src/main/resources/data.sql
> +INSERT INTO mpa (mpa_name)
По поводу MERGE не очень понятно. Я же не пытаюсь синхронизовать 2 таблицы

2023-04-03 21:57 UTC, pavlovartem97 commented on src/main/resources/data.sql
> +INSERT INTO mpa (mpa_name)
MERGE INTO mpa new
    USING (SELECT * FROM mpa) old
        ON (new.MPA_ID = old.MPA_ID)
    WHEN NOT MATCHED THEN INSERT (MPA_NAME) VALUES ('G');

Вот такое работает, но я не могу при этом проставить несколько столбцов. Либо писать много запросов на слияние

2023-04-03 22:15 UTC, pavlovartem97 commented on src/main/resources/data.sql
> +INSERT INTO mpa (mpa_name)
https://www.tutorialspoint.com/h2_database/h2_database_merge.htm

2023-04-03 22:16 UTC, pavlovartem97 commented on src/main/resources/data.sql
> +INSERT INTO mpa (mpa_name)
Кажется разобрался, но хотя бы надо было подсказку оставить, чтобы я искал в диалекте H2. У нас на курсе было 
INSERT INTO products (id, name, price, category) 
VALUES (1, 'Шампунь 2', 1200, 'косметика') 
ON CONFLICT DO NOTHING;

2023-04-03 22:34 UTC, pavlovartem97 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA CASCADE;
![image](https://user-images.githubusercontent.com/111424160/229641501-41b375fb-baa7-4be7-a565-e9ffcf102da8.png)

2023-04-03 22:34 UTC, pavlovartem97 commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA CASCADE;
Если удалить DROP TABLE IF EXISTS * , то рушатся тесты на гитхабе(

2023-04-04 07:04 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/favourite/FavouriteDbStorage.java
> +public class FavouriteDbStorage implements FavouriteStorage {
Связующая таблица - часть логики другой сущности

2023-04-04 07:07 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    }
Окей

2023-04-04 07:08 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmExtractor.java
> +        while (rs.next()) {
Я понял для чего это , просто на заметку - для списка можно делать отдельный запрос

2023-04-04 07:10 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA CASCADE;
Судя пол логам, апи тесты рушатся из-за того, что падают твои юнит тесты

2023-04-04 07:30 UTC, kalitva approved these changes

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Лишний логер

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public boolean equals(Object o) {
Вроде можно указать ломбоку чтобы он сгенерил equals только для указанных поле, используя
 `@EqualsAndHashCode(onlyExplicitlyIncluded = true)`, попробуй

https://projectlombok.org/features/EqualsAndHashCode (первый абзац)

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbImlp/GenreDbStorage.java
> +        } catch (DataAccessException ex) {
`} catch (EmptyResultDataAccessException ex) {` Как-то так называется исключение, которое выбрасывается, если строка БД не найдена

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbImlp/UserDbStorage.java
> +        getUserById(user.getId());
Эти проверки должны быть в сервисах

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryImpl/InMemoryFilmStorage.java
> +package ru.yandex.practicum.filmorate.storage.InMemoryImpl;
Назови пакет по конвенции
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2023-04-04 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryImpl/InMemoryFriendStorage.java
> +import java.util.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-04-04 07:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          Film film = filmStorage.getFilmById(filmId);
Лучше использовать другой запрос
`return jdbcTemplate.queryForObject("select count(1) from film where if = ?", Long.class, id) == 1`

2023-04-09 13:39 UTC, merged